version: '3.9'

services:
 
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    build:
      context: ./requirements/nginx
    volumes:
      - wordpress-volume:/var/www/app
    networks:
      - inception
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: unless-stopped
    build:
      context: ./requirements/wordpress
      args:
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_DATABASE=${DB_DATABASE}
    volumes:
      - wordpress-volume:/var/www/app
    networks:
      - inception

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    build:
      context: ./requirements/mariadb
      args:
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_DATABASE=${DB_DATABASE}
        - WP_ROOT_USERNAME=${WP_ROOT_USERNAME}
        - WP_ROOT_PASSWORD=${WP_ROOT_PASSWORD}
        - WP_USER_PASSWORD=${WP_USER_PASSWORD}
    volumes:
      - database-volume:/var/lib/mysql
    networks:
      - inception
    ports:
      - "3306:3306"


volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: ${VOL_WWW_PATH}
      o: bind
  database-volume:
    driver: local
    driver_opts:
      type: none
      device: ${VOL_DB_PATH}
      o: bind


networks:
  inception:
    driver: bridge

