version: '3.9'

services:
 
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      args:
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_DATABASE=${DB_DATABASE}
        - DB_HOSTNAME=${DB_HOSTNAME}
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_DATABASE=${DB_DATABASE}
    volumes:
      - database_volume:/var/lib/mysql
    networks:
      - inception
    restart: always


volumes:
  database_volume:
    driver: local
    driver_opts:
      type: none
      device: ${VOL_DB_PATH}
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: ${VOL_WWW_PATH}
      o: bind


networks:
  inception:
    driver: bridge

